Repository aasm/aasm, pull requests merged in 2018-02, with the labels that each got.

#496 Remove trailing space from error message
  lib/aasm/errors.rb
  spec/unit/exception_spec.rb
  spec/unit/transition_spec.rb
Labels: error handling

#495 Add tests for Rails 5.1
  .travis.yml
  Appraisals
  gemfiles/rails_5.1.gemfile
Labels: testing

#524 Displays ORM versions when running tests
  spec/spec_helpers/active_record.rb
  spec/spec_helpers/dynamoid.rb
  spec/spec_helpers/mongoid.rb
  spec/spec_helpers/redis.rb
  spec/spec_helpers/sequel.rb
Labels: testing, waiting for response
