Repository aasm/aasm, pull requests merged in 2025-06, with the labels that each got.

#862 Fix the build
  .github/workflows/build.yml
  .gitignore
  aasm.gemspec
  gemfiles/rails_4.2.gemfile
  gemfiles/rails_4.2_mongoid_5.gemfile
  gemfiles/rails_4.2_nobrainer.gemfile
  gemfiles/rails_5.2.gemfile
  spec/unit/persistence/active_record_persistence_multiple_spec.rb
  spec/unit/persistence/active_record_persistence_spec.rb
Labels: testing

#868 Trigger CI on Pull Request
  .github/workflows/build.yml
Labels: testing

#853 CI against Rails 7.2
  .github/workflows/build.yml
  gemfiles/rails_7.2.gemfile
Labels: testing, rails

#860 CI against Rails 8.0
  .github/workflows/build.yml
  gemfiles/rails_8.0.gemfile
Labels: testing, rails

#857 Ruby 3.2 compatibility ✅
  lib/aasm/core/invokers/base_invoker.rb
  lib/aasm/core/invokers/class_invoker.rb
  lib/aasm/core/invokers/literal_invoker.rb
  spec/models/class_with_keyword_arguments.rb
  spec/models/event_with_keyword_arguments.rb
  spec/unit/class_with_keyword_arguments_spec.rb
  spec/unit/event_with_keyword_arguments_spec.rb
  spec/unit/invokers/class_invoker_spec.rb
  spec/unit/invokers/literal_invoker_spec.rb
Labels: ruby

#869 Update `actions/checkout` to its latest version v4
  .github/workflows/build.yml
Labels: admin

#867 Add builds for Ruby 3.3 and 3.4
  .github/workflows/build.yml
Labels: testing, ruby, admin

#759 Add changelog_uri to gemspec
  aasm.gemspec
Labels: admin
